### ISSUE TITLE
improper key 

### ISSUE THREAD

**Issue by freewheel70** [12138mICHAEL1111/redux-demo#2]
https://github.com/12138mICHAEL1111/redux-demo/blob/74179e1162c6b2637775992bff88b20b0e774092/src/components/useRedux.js#L21

Please rethink about the purpose of key in React.

if key={item+index}, please consider the following situation:
1. the food list is ['rice', 'noodle', 'fish']
2. remove 'rice'
How many list items will be re-render ?

**Comment by 12138mICHAEL1111** [comment]
2 items would be re-rendered, namely noodle and fish. If index is used as key, the key of noodle would be 1 and key of fish would be 2. After rice is deleted, the key of noodle would be 0 and fish would be 1, the keys of the 2 items are changed, so noodle and fish are re-rendered. So my code is wrong, using object to represent food is a better way
